#!/usr/bin/env bash


################################################################################
### Head: Url
##

# * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/standalone/bin/demo-ctrl

##
### Tail: Url
################################################################################


################################################################################
### Head: Init
##
set -e ## for Exit immediately if a command exits with a non-zero status.
THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"
THE_CMD_FILE_NAME="$(basename "$0")"
##
### Tail: Init
################################################################################


################################################################################
### Head: Util / Debug
##

util_debug_echo () {
	if is_debug; then
		echo "$@" 1>&2
	fi
}

util_error_echo () {
	echo "$@" 1>&2
}

##
### Head: Util / Debug
################################################################################


################################################################################
### Head: Base
##

## THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"

find_dir_path () {
	if ! [ -d "$(dirname -- "$1")" ]; then
		dirname -- "$1"
		return 1
	fi
	echo "$(cd -- "$(dirname -- "$1")" ; pwd)"
}

## THIS_BASE_DIR_PATH="$(find_dir_path "$0")"

## $ export DEBUG_TINT2_THEME_LAUNCHER=true
is_debug () {
	if [ "$DEBUG_TINT2_THEME_LAUNCHER" = "true" ]; then
		return 0
	fi

	return 1
}

is_not_debug () {
	! is_debug
}

base_var_init () {

	#THE_PLAN_DIR_PATH="$(find_dir_path "$THE_BASE_DIR_PATH/../.")"
	THE_PLAN_DIR_PATH="$(find_dir_path "$THE_BASE_DIR_PATH/.")"

	THE_CMD_VERSION='0.1'

	THE_CMD_DIR_PATH="${THE_BASE_DIR_PATH}"

	if [ "none${THE_CMD_FILE_NAME}" = 'none' ]; then
		THE_CMD_FILE_NAME='tint2-theme-launcher'
	fi

	THE_CMD_FILE_PATH="${THE_CMD_DIR_PATH}/${THE_CMD_FILE_NAME}"

	## https://github.com/samwhelp/note-about-tint2/blob/gh-pages/_demo/config/tint2-config/modeling-theme-basic/tool/tint2-theme-launcher/tint2-theme-launcher
	THE_SELF_UPDATE_URL='https://raw.githubusercontent.com/samwhelp/note-about-tint2/gh-pages/_demo/config/tint2-config/modeling-theme-basic/tool/tint2-theme-launcher/tint2-theme-launcher'


	THE_TMP_DIR_PATH="/tmp"


	THE_ASSET_DIR_NAME="asset"
	THE_ASSET_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_ASSET_DIR_NAME"

	THE_VAR_DIR_NAME="var"
	THE_VAR_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_VAR_DIR_NAME"

	THE_PROFILE_DIR_NAME=".${THE_CMD_FILE_NAME}-profile"
	THE_PROFILE_DIR_PATH="$HOME/$THE_PROFILE_DIR_NAME"

	THE_PROJECT_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_PROJECT_DIR_PATH="$HOME/.local/share/$THE_PROJECT_DIR_NAME"

	THE_CONFIG_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_CONFIG_DIR_PATH="$HOME/.config/$THE_CONFIG_DIR_NAME"

	THE_CACHE_DIR_NAME="${THE_CMD_FILE_NAME}"
	THE_CACHE_DIR_PATH="$HOME/.cache/$THE_CACHE_DIR_NAME"



	##
	## tint2
	##
	THE_TINT2_PLAN_DIR_NAME="tint2"
	THE_TINT2_PLAN_SYSTEM_DIR_PATH="/usr/share/${THE_TINT2_PLAN_DIR_NAME}"
	THE_TINT2_PLAN_PERSON_DIR_PATH="${HOME}/.config/${THE_TINT2_PLAN_DIR_NAME}"


	THE_TINT2_HELPER_DIR_NAME="helper"
	THE_TINT2_THEME_ROOT_DIR_NAME="theme"

	THE_TINT2_THEME_ROOT_SYSTEM_DIR_PATH="${THE_TINT2_PLAN_SYSTEM_DIR_PATH}/${THE_TINT2_THEME_ROOT_DIR_NAME}"
	THE_TINT2_THEME_ROOT_PERSON_DIR_PATH="${THE_TINT2_PLAN_PERSON_DIR_PATH}/${THE_TINT2_THEME_ROOT_DIR_NAME}"

	THE_TINT2_HELPER_SYSTEM_DIR_PATH="${THE_TINT2_PLAN_SYSTEM_DIR_PATH}/${THE_TINT2_HELPER_DIR_NAME}"
	THE_TINT2_HELPER_PERSON_DIR_PATH="${THE_TINT2_PLAN_PERSON_DIR_PATH}/${THE_TINT2_HELPER_DIR_NAME}"




	##
	## tint2 tint2-session
	##
	THE_TINT2_SESSION_PLAN_DIR_NAME="tint2-session"
	THE_TINT2_SESSION_PLAN_SYSTEM_DIR_PATH="/usr/share/${THE_TINT2_SESSION_PLAN_DIR_NAME}"
	THE_TINT2_SESSION_PLAN_PERSON_DIR_PATH="${HOME}/.config/${THE_TINT2_SESSION_PLAN_DIR_NAME}"


	THE_TINT2_SESSION_HELPER_SYSTEM_DIR_PATH="${THE_TINT2_SESSION_PLAN_SYSTEM_DIR_PATH}/${THE_TINT2_HELPER_DIR_NAME}"
	THE_TINT2_SESSION_HELPER_PERSON_DIR_PATH="${THE_TINT2_SESSION_PLAN_PERSON_DIR_PATH}/${THE_TINT2_HELPER_DIR_NAME}"

	THE_TINT2_SESSION_THEME_ROOT_SYSTEM_DIR_PATH="${THE_TINT2_SESSION_PLAN_SYSTEM_DIR_PATH}/${THE_TINT2_THEME_ROOT_DIR_NAME}"
	THE_TINT2_SESSION_THEME_ROOT_PERSON_DIR_PATH="${THE_TINT2_SESSION_PLAN_PERSON_DIR_PATH}/${THE_TINT2_THEME_ROOT_DIR_NAME}"







}

base_var_dump () {

	is_not_debug && return 0

	util_debug_echo
	util_debug_echo "################################################################################"
	util_debug_echo "### Head: var_dump"
	util_debug_echo "##"
	util_debug_echo "#"


	util_debug_echo "THE_PLAN_DIR_PATH=$THE_PLAN_DIR_PATH"

	util_debug_echo "THE_CMD_FILE_NAME=$THE_CMD_FILE_NAME"
	util_debug_echo "THE_CMD_FILE_PATH=$THE_CMD_FILE_PATH"
	util_debug_echo "THE_CMD_DIR_PATH=$THE_CMD_DIR_PATH"

	util_debug_echo "THE_SELF_UPDATE_URL=$THE_SELF_UPDATE_URL"


	util_debug_echo "THE_TMP_DIR_PATH=$THE_TMP_DIR_PATH"


	util_debug_echo "THE_ASSET_DIR_NAME=$THE_ASSET_DIR_NAME"
	util_debug_echo "THE_ASSET_DIR_PATH=$THE_ASSET_DIR_PATH"

	util_debug_echo "THE_VAR_DIR_NAME=$THE_VAR_DIR_NAME"
	util_debug_echo "THE_VAR_DIR_PATH=$THE_VAR_DIR_PATH"




	util_debug_echo "THE_PROFILE_DIR_NAME=$THE_PROFILE_DIR_NAME"
	util_debug_echo "THE_PROFILE_DIR_PATH=$THE_PROFILE_DIR_PATH"

	util_debug_echo "THE_PROJECT_DIR_NAME=$THE_PROJECT_DIR_NAME"
	util_debug_echo "THE_PROJECT_DIR_PATH=$THE_PROJECT_DIR_PATH"

	util_debug_echo "THE_CONFIG_DIR_NAME=$THE_CONFIG_DIR_NAME"
	util_debug_echo "THE_CONFIG_DIR_PATH=$THE_CONFIG_DIR_PATH"

	util_debug_echo "THE_CACHE_DIR_NAME=$THE_CACHE_DIR_NAME"
	util_debug_echo "THE_CACHE_DIR_PATH=$THE_CACHE_DIR_PATH"




	##
	## tint2
	##
	util_debug_echo "THE_TINT2_PLAN_DIR_NAME=${THE_TINT2_PLAN_DIR_NAME}"
	util_debug_echo "THE_TINT2_PLAN_SYSTEM_DIR_PATH=${THE_TINT2_PLAN_SYSTEM_DIR_PATH}"
	util_debug_echo "THE_TINT2_PLAN_PERSON_DIR_PATH=${THE_TINT2_PLAN_PERSON_DIR_PATH}"

	util_debug_echo "THE_TINT2_HELPER_DIR_NAME=${THE_TINT2_HELPER_DIR_NAME}"
	util_debug_echo "THE_TINT2_THEME_ROOT_DIR_NAME=${THE_TINT2_THEME_ROOT_DIR_NAME}"


	util_debug_echo "THE_TINT2_HELPER_SYSTEM_DIR_PATH=${THE_TINT2_HELPER_SYSTEM_DIR_PATH}"
	util_debug_echo "THE_TINT2_HELPER_PERSON_DIR_PATH=${THE_TINT2_HELPER_PERSON_DIR_PATH}"

	util_debug_echo "THE_TINT2_THEME_ROOT_SYSTEM_DIR_PATH=${THE_TINT2_THEME_ROOT_SYSTEM_DIR_PATH}"
	util_debug_echo "THE_TINT2_THEME_ROOT_PERSON_DIR_PATH=${THE_TINT2_THEME_ROOT_PERSON_DIR_PATH}"


	##
	## tint2 session
	##
	util_debug_echo "THE_TINT2_SESSION_PLAN_DIR_NAME=${THE_TINT2_SESSION_PLAN_DIR_NAME}"
	util_debug_echo "THE_TINT2_SESSION_PLAN_SYSTEM_DIR_PATH=${THE_TINT2_SESSION_PLAN_SYSTEM_DIR_PATH}"
	util_debug_echo "THE_TINT2_SESSION_PLAN_PERSON_DIR_PATH=${THE_TINT2_SESSION_PLAN_PERSON_DIR_PATH}"

	util_debug_echo "THE_TINT2_SESSION_HELPER_SYSTEM_DIR_PATH=${THE_TINT2_SESSION_HELPER_SYSTEM_DIR_PATH}"
	util_debug_echo "THE_TINT2_SESSION_HELPER_PERSON_DIR_PATH=${THE_TINT2_SESSION_HELPER_PERSON_DIR_PATH}"

	util_debug_echo "THE_TINT2_SESSION_THEME_ROOT_SYSTEM_DIR_PATH=${THE_TINT2_SESSION_THEME_ROOT_SYSTEM_DIR_PATH}"
	util_debug_echo "THE_TINT2_SESSION_THEME_ROOT_PERSON_DIR_PATH=${THE_TINT2_SESSION_THEME_ROOT_PERSON_DIR_PATH}"








	util_debug_echo "#"
	util_debug_echo "##"
	util_debug_echo "### Tail: var_dump"
	util_debug_echo "################################################################################"
	util_debug_echo
}


base_var_init

base_var_dump

##
### Tail: Base
################################################################################


################################################################################
### Head: Util / Command
##

is_function_exist () {
	if type -p "$1" > /dev/null; then
		return 0
	else
		return 1
	fi
}

# is_command_exist () {
# 	if command -v "$1" > /dev/null; then
# 		return 0
# 	else
# 		return 1
# 	fi
# }

is_command_exist () {
	if [ -x "$(command -v $1)" ]; then
		return 0
	else
		return 1
	fi
}

##
### Tail: Util / Command
################################################################################


################################################################################
### Head: Util / Process
##

util_stop_all ()  {

	if is_command_exist 'pkill'; then
		util_stop_all_by_pkill "$1"
		return 0
	fi

	if is_command_exist 'killall'; then
		util_stop_all_by_killall "$1"
		return 0
	fi

	return 0
}

util_stop_all_by_pkill () {

	if pkill "$1"; then
		return 0
	fi

	return 0
}

util_stop_all_by_killall () {

	if killall -q -9 "$1"; then
		return 0
	fi

	return 0

}

##
### Tail: Util / Process
################################################################################


################################################################################
### Head: Util / SubCmd
##

sub_cmd_find_function_name () {
	echo "act_run_$1"
}

##
### Tail: Util / SubCmd
################################################################################


################################################################################
### Head: Util / SelfUpdate
##

util_make_bin_dir () {
	mkdir -p "$HOME/bin"
}

util_make_tmp_dir () {
	THE_TMP_DIR_PATH="/tmp/tmp.$$.$RANDOM"
	mkdir "$THE_TMP_DIR_PATH"
}

util_self_update_download_to_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	wget -c "$THE_SELF_UPDATE_URL" -O "$tmp_file_path"

}

util_self_update_install_from_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	echo "install -m 755 $tmp_file_path $THE_CMD_FILE_PATH"
	install -m 755 "$tmp_file_path" "$THE_CMD_FILE_PATH"

}

util_self_update_check_cmd_exists () {

	if ! [ -f "$THE_CMD_FILE_PATH" ]; then ## file not exists
		return 0
	fi


	echo "File is exists:" "$THE_CMD_FILE_PATH"
	echo

	echo "Try to backup:"
	echo

	local now=$(date +%Y%m%d_%s)
	local bak_dir_path="${THE_CMD_FILE_PATH}.bak"
	local bak_file_path="${bak_dir_path}/${THE_CMD_FILE_NAME}.bak.$now"

	mkdir -p $bak_dir_path

	mv -v "$THE_CMD_FILE_PATH" "${bak_file_path}"

	if [ "$?" != "0" ]; then
		echo
		echo 'Backup Failure!'
		exit 1
	fi

	echo

	return 0
}

util_self_update_print_version () {
	echo
	echo "Current Version:"

	"$THE_CMD_FILE_PATH" version
}

util_self_update () {

	util_make_bin_dir

	util_make_tmp_dir

	util_self_update_download_to_tmp_dir

	util_self_update_check_cmd_exists && util_self_update_install_from_tmp_dir


	util_self_update_print_version

}


main_version () {
	echo $THE_CMD_VERSION
}

util_self_actions () {
	grep '^act_run' "${THE_CMD_FILE_PATH}" | cut -d ' ' -f 1 | awk -F 'act_run_' '{print $2}' | sort -u
}

##
### Tail: Util / SelfUpdate
################################################################################


################################################################################
### Head: Util / File Exist Check
##

util_check_target_file_exist () {

	local target="$1"

	##
	## $ help test
	##

	#if [ "none${target}" = "none" ]; then
	#	return 1
	#fi

	if [ -z "${target}" ]; then
		util_error_echo
		util_error_echo '##'
		util_error_echo '## util_check_target_file_exist: Empty input'
		util_error_echo '##'
		util_error_echo
		return 1
	fi

	if [ -f "${target}" ]; then
		echo "${target}"
		return 0
	fi

	return 1

}

##
### Tail: Util / File Exist Check
################################################################################


################################################################################
### Head: Util / Dir Exist Check
##

util_check_target_dir_exist () {

	local target="$1"

	##
	## $ help test
	##

	#if [ "none${target}" = "none" ]; then
	#	return 1
	#fi

	if [ -z "${target}" ]; then
		util_error_echo
		util_error_echo '##'
		util_error_echo '## util_check_target_dir_exist: Empty input'
		util_error_echo '##'
		util_error_echo
		return 1
	fi

	if [ -d "${target}" ]; then
		echo "${target}"
		return 0
	fi

	return 1

}

##
### Tail: Util / Dir Exist Check
################################################################################


################################################################################
### Head: Util / Module Dir Check
##

is_tint2_theme_dir () {

	local target_dir_path="$1"
	local check_file_path="${target_dir_path}/start.sh"

	if [ ! -f "${check_file_path}" ]; then
		return 1
	fi

	return 0
}

is_not_tint2_theme_dir () {

	local target_dir_path="$1"
	local check_file_path="${target_dir_path}/start.sh"

	if [ -f "${check_file_path}" ]; then
		return 1
	fi

	return 0

}

##
### Tail: Util / Module Dir Check
################################################################################


################################################################################
### Head: Sys / Module Name List
##

sys_tint2_theme_name_list () {

	#util_error_echo "sys_tint2_theme_name_list"
	#util_error_echo "$@"


	local choose="$1"
	local base_dir_path="$1"
	local sub_dir_name=''
	local sub_dir_path=''


	if ! base_dir_path="$(util_check_target_dir_exist "${choose}")"; then
		util_error_echo
		util_error_echo '##'
		util_error_echo '## Dir Not Exist: '
		util_error_echo '##'
		util_error_echo
		util_error_echo "You choose dir: [${choose}]"
		util_error_echo
		return 0
	fi


	cd "${base_dir_path}"

	####for sub_dir_name in *; do  ## not use this, if empty dir

	for sub_dir_name in $(ls ./ -1); do

		sub_dir_path="${base_dir_path}/${sub_dir_name}"

		if is_not_tint2_theme_dir "${sub_dir_path}"; then
			continue
		fi

		echo "${sub_dir_name}"
	done

	cd "${OLDPWD}"

	##
	## $ man cd | grep OLDPWD
	##

}

##
### Tail: Sys / Module Name List
################################################################################


################################################################################
### Head: Sys / Target Script Execute
##

sys_tint2_target_script_execute () {

	#util_error_echo "sys_tint2_target_script_execute"
	#util_error_echo "$@"


	local choose_file_path="$1"
	local target_file_path="$1"


	if ! target_file_path="$(util_check_target_file_exist $choose_file_path)"; then
		util_error_echo
		util_error_echo '##'
		util_error_echo '## Script Not Exist: '
		util_error_echo '##'
		util_error_echo
		util_error_echo "You choose file: [${choose_file_path}]"
		util_error_echo
		return 1
	fi


	if [ -x "$target_file_path" ]; then
		util_error_echo
		util_error_echo '##'
		util_error_echo '## Execute Script: '
		util_error_echo '##'
		util_error_echo
		util_error_echo "Script file: [${target_file_path}]"
		util_error_echo

		"$target_file_path"
	fi

	return 0

}

##
### Tail: Sys / Target Script Execute
################################################################################


################################################################################
### Head: Mod / Module Name List
##

mod_tint2_theme_name_list () {

	#util_error_echo "mod_tint2_theme_name_list"
	#util_error_echo "$@"

	##
	## tint2-theme-launcher list
	##

	local base_dir_path="${THE_TINT2_THEME_ROOT_PERSON_DIR_PATH}"


	sys_tint2_theme_name_list "$base_dir_path"

}

##
### Tail: Mod / Module Name List
################################################################################


################################################################################
### Head: Mod / Module Action Execute
##

mod_tint2_script_execute_by_module_action () {

	#util_error_echo "mod_tint2_script_execute_by_module_action"
	#util_error_echo "$@"

	local base_dir_path="${THE_TINT2_THEME_ROOT_PERSON_DIR_PATH}"

	local choose_module="$1"
	local choose_action="$2"
	local script_file_path="${base_dir_path}/${choose_module}/${choose_action}.sh"

	sys_tint2_target_script_execute "${script_file_path}"

}

##
### Tail: Mod / Module Action Execute
################################################################################


################################################################################
### Head: Mod / Module / install
##

mod_tint2_theme_start () {

	#util_error_echo "mod_tint2_theme_start"
	#util_error_echo "$@"


	local choose_module="$1"
	local choose_action="start"

	util_error_echo
	util_error_echo '##'
	util_error_echo "## Module: ${choose_module}"
	util_error_echo "## Action: ${choose_action}"
	util_error_echo '##'
	util_error_echo


	mod_tint2_script_execute_by_module_action "${choose_module}" "${choose_action}"

}

##
### Tail: Mod / Module / install
################################################################################


################################################################################
### Head: Mod / Module / package-install
##

mod_tint2_theme_stop () {

	#util_error_echo "mod_tint2_theme_stop"
	#util_error_echo "$@"


	local choose_module="$1"
	local choose_action="stop"

	util_error_echo
	util_error_echo '##'
	util_error_echo "## Module: ${choose_module}"
	util_error_echo "## Action: ${choose_action}"
	util_error_echo '##'
	util_error_echo


	mod_tint2_script_execute_by_module_action "${choose_module}" "${choose_action}"

}

##
### Tail: Mod / Module / package-install
################################################################################


################################################################################
### Head: Mod / Module / config-install
##

mod_tint2_theme_restart () {

	#util_error_echo "mod_tint2_theme_restart"
	#util_error_echo "$@"


	local choose_module="$1"
	local choose_action="restart"

	util_error_echo
	util_error_echo '##'
	util_error_echo "## Module: ${choose_module}"
	util_error_echo "## Action: ${choose_action}"
	util_error_echo '##'
	util_error_echo


	mod_tint2_script_execute_by_module_action "${choose_module}" "${choose_action}"

}

##
### Tail: Mod / Module / config-install
################################################################################


################################################################################
### Head: Mod / Fzf / Module / install
##

mod_tint2_fzf_theme_start () {

	#util_error_echo "mod_tint2_fzf_theme_start"
	#util_error_echo "$@"


	if ! is_command_exist 'fzf'; then
		util_error_echo
		util_error_echo '##'
		util_error_echo '## Need: fzf'
		util_error_echo '## * https://github.com/junegunn/fzf'
		util_error_echo '##'
		util_error_echo '## Mabox Install:'
		util_error_echo '## $ sudo pacman -Sy --needed fzf'
		util_error_echo '##'
		util_error_echo
		return 1
	fi

	local choose_action="install"
	local choose_module="$(mod_tint2_theme_name_list | fzf)"

	util_error_echo
	util_error_echo '##'
	util_error_echo "## Selected: [${choose_module}]"
	util_error_echo '##'


	if [ -z "${choose_module}" ]; then
		util_error_echo
		util_error_echo "## Not Selected"
		util_error_echo
		return 1
	fi

	mod_tint2_theme_start "${choose_module}" "${choose_action}"

}

##
### Tail: Mod / Fzf / Module / install
################################################################################


################################################################################
### Head: Mod / Fzf / Module / package-install
##

mod_tint2_fzf_theme_stop () {

	#util_error_echo "mod_tint2_fzf_theme_stop"
	#util_error_echo "$@"


	if ! is_command_exist 'fzf'; then
		util_error_echo
		util_error_echo '##'
		util_error_echo '## Need: fzf'
		util_error_echo '## * https://github.com/junegunn/fzf'
		util_error_echo '##'
		util_error_echo '## Mabox Install:'
		util_error_echo '## $ sudo pacman -Sy --needed fzf'
		util_error_echo '##'
		util_error_echo
		return 1
	fi

	local choose_action="package-install"
	local choose_module="$(mod_tint2_theme_name_list | fzf)"

	util_error_echo
	util_error_echo '##'
	util_error_echo "## Selected: [${choose_module}]"
	util_error_echo '##'


	if [ -z "${choose_module}" ]; then
		util_error_echo
		util_error_echo "## Not Selected"
		util_error_echo
		return 1
	fi

	mod_tint2_theme_stop "${choose_module}" "${choose_action}"

}

##
### Tail: Mod / Fzf / Module / package-install
################################################################################


################################################################################
### Head: Mod / Fzf / Module / config-install
##

mod_tint2_fzf_theme_restart () {

	#util_error_echo "mod_tint2_fzf_theme_restart"
	#util_error_echo "$@"


	if ! is_command_exist 'fzf'; then
		util_error_echo
		util_error_echo '##'
		util_error_echo '## Need: fzf'
		util_error_echo '## * https://github.com/junegunn/fzf'
		util_error_echo '##'
		util_error_echo '## Mabox Install:'
		util_error_echo '## $ sudo pacman -Sy --needed fzf'
		util_error_echo '##'
		util_error_echo
		return 1
	fi

	local choose_action="config-install"
	local choose_module="$(mod_tint2_theme_name_list | fzf)"

	util_error_echo
	util_error_echo '##'
	util_error_echo "## Selected: [${choose_module}]"
	util_error_echo '##'


	if [ -z "${choose_module}" ]; then
		util_error_echo
		util_error_echo "## Not Selected"
		util_error_echo
		return 1
	fi

	mod_tint2_theme_restart "${choose_module}" "${choose_action}"

}

##
### Tail: Mod / Fzf / Module / config-install
################################################################################


################################################################################
### Head: SubCmd
##

act_run_help () {
	main_usage "$@"
}

act_run_version () {
	main_version "$@"
}

act_run_self_update () {
	util_self_update "$@"
}

act_run_self_actions () {
	util_self_actions "$@"
}



act_run_theme_list () {
	#util_error_echo "act_run_theme_list"
	mod_tint2_theme_name_list "$@"
}


act_run_theme_start () {
	#util_error_echo "act_run_theme_start"
	mod_tint2_theme_start "$@"
}


act_run_theme_stop () {
	#util_error_echo "act_run_theme_stop"
	mod_tint2_theme_stop "$@"
}


act_run_theme_restart () {
	#util_error_echo "act_run_theme_restart"
	mod_tint2_theme_restart "$@"
}


act_run_fzf_theme_start () {
	#util_error_echo "act_run_fzf_theme_start"
	mod_tint2_fzf_theme_start "$@"
}


act_run_fzf_theme_stop () {
	#util_error_echo "act_run_fzf_theme_stop"
	mod_tint2_fzf_theme_stop "$@"
}


act_run_fzf_theme_restart () {
	#util_error_echo "act_run_fzf_theme_restart"
	mod_tint2_fzf_theme_restart "$@"
}

##
### Tail: SubCmd
################################################################################


################################################################################
### Head: Main
##

main_usage () {
	##local cmd_name="$0"
	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF
Usage:
	$ $cmd_name [action]

Example:

	## help

		$ $cmd_name
		$ $cmd_name help

	## version

		$ $cmd_name version

	## self_update

		$ $cmd_name self_update

	## self_actions

		$ $cmd_name self_actions


	## theme

		$ $cmd_name theme_list

		$ $cmd_name theme_start {theme_name}

		$ $cmd_name theme_stop {theme_name}

		$ $cmd_name theme_restart {theme_name}


	## fzf theme

		$ $cmd_name fzf_theme_start

		$ $cmd_name fzf_theme_stop

		$ $cmd_name fzf_theme_restart


Debug:
	$ export DEBUG_TINT2_THEME_LAUNCHER=true

EOF

}

main_check_args_size () {
	if [ $1 -le 0 ]; then
		shift
		main_run_default_sub_cmd "$@"
		exit 1
	fi
}

main_run_default_sub_cmd () {
	main_usage "$@"
}

main_run_sub_cmd () {

	local sub_cmd="$1"

	shift

	local function_name="$(sub_cmd_find_function_name "$sub_cmd")"

	if ! is_function_exist "$function_name" ; then

		util_debug_echo
		util_debug_echo '##'
		util_debug_echo "## [Debug] sub_cmd_function_not_exist: sub_cmd=$sub_cmd; function_name=$function_name"
		util_debug_echo '##'
		util_debug_echo

		main_run_default_sub_cmd "$@"

		return 1

	fi

	"$function_name" "$@" ## run sub cmd function


}

## Start
main_check_args_size $# "$@"

main_run_sub_cmd "$@"

##
### Tail: Main
################################################################################
